# Generated by Django 5.1 on 2024-09-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_enquiry_user_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='1dbf04', max_length=6),
        ),
    ]
