# Generated by Django 5.1 on 2024-09-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_enquiry_response_alter_otptoken_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='b8576f', max_length=6),
        ),
    ]
