# Generated by Django 5.1 on 2024-09-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_enquiry_is_replied_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='is_replied',
            new_name='replied',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='0a7991', max_length=6),
        ),
    ]
