# Generated by Django 5.1 on 2024-09-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_rename_is_replied_enquiry_replied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='reply_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='768d66', max_length=6),
        ),
    ]
