# Generated by Django 5.1 on 2024-09-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_event_username_event_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='fa3e05', max_length=6),
        ),
    ]
