# Generated by Django 5.1 on 2024-09-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='rejected', max_length=20),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='8a02f6', max_length=6),
        ),
    ]
