# Generated by Django 5.1 on 2024-09-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_event_deleted_by_event_deletion_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='b09899', max_length=6),
        ),
    ]
