# Generated by Django 5.1 on 2024-09-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_event_updated_at_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='deletion_message',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='99ead9', max_length=6),
        ),
    ]
