# Generated by Django 5.1 on 2024-09-17 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_rename_deletion_message_event_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='f81797', max_length=6),
        ),
    ]
