# Generated by Django 5.1 on 2024-09-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_calendarevent_user_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='user',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='6cebf8', max_length=6),
        ),
    ]
