# Generated by Django 5.1 on 2024-09-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_calendarevent_user_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='522d32', max_length=6),
        ),
    ]
