# Generated by Django 5.1 on 2024-09-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_calendarevent_username_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='user',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='4a3895', max_length=6),
        ),
    ]
