# Generated by Django 5.1 on 2024-09-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_calendarevent_user_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='e6e650', max_length=6),
        ),
    ]
