# Generated by Django 5.1 on 2024-09-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_contact_delete_contactmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='doctor',
            field=models.CharField(choices=[('Dr. Smith', 'Dr. Smith'), ('Dr. Johnson', 'Dr. Johnson'), ('Dr. Williams', 'Dr. Williams')], default='Dr. Smith', max_length=200),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='room',
            field=models.CharField(choices=[('Room 1', 'Room 1'), ('Room 2', 'Room 2'), ('Room 3', 'Room 3')], default='Room 1', max_length=200),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='6b0c0d', max_length=6),
        ),
    ]
