# Generated by Django 5.1 on 2024-09-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_alter_calendarevent_doctor_alter_calendarevent_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='doctor',
            field=models.CharField(choices=[('Dr. Sanjay', 'Dr. Sanjay'), ('Dr. Raji', 'Dr. Raji'), ('Dr. Suhas', 'Dr. Suhas'), ('Dr. Sachin', 'Dr. Sachin'), ('Dr. Divya', 'Dr. Divya')], default='Not Selected', max_length=200),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='room',
            field=models.CharField(choices=[('Room 1', 'Room 1'), ('Room 2', 'Room 2'), ('Room 3', 'Room 3'), ('Room 4', 'Room 4'), ('Room 5', 'Room 5')], default='Not Selected', max_length=200),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='04c390', max_length=6),
        ),
    ]
