# Generated by Django 5.1 on 2024-09-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_alter_calendarevent_doctor_alter_calendarevent_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='e3adc4', max_length=6),
        ),
    ]
