from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name='home'),
    path("signup", views.signup, name="signup"),
    path("verify-email/<str:username>", views.verify_email, name="verify-email"),
    path("resend-otp", views.resend_otp, name="resend-otp"),
    path("login", views.signin, name="signin"),
    path('reset_password/', views.reset_password_view, name='reset_password'),
    path('admin_reset_password/', views.admin_reset_password_view, name='admin_reset_password'),
    path('admin_login/', views.login_view, name='admin_login'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path("home1", views.home1, name='home1'),
    path("predict/", views.predict, name='predict'),
    path("predict/results/", views.result, name='result'),
    path('users/', views.user_list, name='user_list'),
    path('users/delete/<int:user_id>/', views.delete_user, name='delete_user'),
    path('admin_prediction_list/', views.admin_prediction_list, name='admin_prediction_list'),
    path('user_prediction_list/', views.user_prediction_list, name='user_prediction_list'),
    path('download_prediction/<int:prediction_id>/', views.download_prediction, name='download_prediction'),
    path('admin_download-prediction/<int:prediction_id>/', views.admin_download_prediction, name='admin_download_prediction'),
    path('delete/<int:prediction_id>/', views.delete_prediction, name='delete_prediction'),
    path('events/', views.event_page, name='event_page'),
    path('api/events/', views.get_events, name='get_events'),
    path('api/events/update/<int:event_id>/', views.update_event, name='update_event'),
    path('api/events/delete/<int:event_id>/', views.delete_event, name='delete_event'),
    path('enquiry/', views.enquiry, name='enquiry'),
    path('admin_enquiry_list/', views.admin_enquiry_list, name='admin_enquiry_list'),
    path('user_enquiry_list/', views.user_enquiry_list, name='user_enquiry_list'),
    path('delete-enquiry/<int:enquiry_id>/', views.delete_enquiry, name='delete_enquiry'),
    path('reply/<int:enquiry_id>/', views.reply_enquiry, name='reply_enquiry'),
    path('api/user_data/', views.get_user_data, name='get_user_data'),
    path('book_schedule/', views.book_event_page, name='book_event_page'),
    path('user_booked_list/', views.user_booked_list, name='user_booked_list'),
    path('user_delete_event/<int:event_id>/', views.user_delete_event, name='user_delete_event'),
    path('admin_booked_list/', views.admin_booked_list, name='admin_booked_list'),
    path('delete_appointment/<int:event_id>/', views.delete_appointment, name='delete_appointment'),
    path('confirm_appointment/<int:event_id>/', views.confirm_appointment, name='confirm_appointment'),
    path('contact/', views.contact_page, name='contact'),
    path('admin_email_list/', views.admin_email_list, name='admin_email_list'),
]
